title = "barath"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Coimbatore, India"
favicon = "/favicon.ico"
firstName = "BARATH"
lastName = "V"
phone = "9342521549"
profileImage = "https://avatars.githubusercontent.com/u/138578026?v=4"
showQr = true
showContact = true
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/barath-v-bb126a237/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/barath-at-github/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
